### ISSUE TITLE
Something inconsistent?

### ISSUE THREAD

**Issue by srees** [d6lts/panels#1]
Panels are rather complex and there are good odds I don't understand what I'm seeing.
Look at panels_ipe/plugins/display_renderers/panels_renderer_ipe.class.php.

For function render_pane_content() on line 112 an undefined variable is being returned if there is no access, instead of the parent function results like the other cases. I assume this is supposed to be $content instead of $output? (gotta love the inconsistency of this codebase, eh?)

**Comment by srees** [comment]
Also, 
panels_ipe/panels_ipe.api.php
Multiple incorrect variables - lines 20, 24, and 26 should be referencing $panels_display instead of $display - or just change the function input to $display.

And, what's with line 26? There is no other code in the entire panels module that references 'awesome_page' - isn't this going to always return FALSE?

**Comment by dsnopek** [comment]
Thanks for the issue! Some of these were fixed in follow-up patches for D7 - I'll look at backporting that this week. The code in `panels_api.api.php` is just documentation, so it's errors won't break anything, but should still be fixed.

**Comment by dsnopek** [comment]
All the things mentioned here were fixed in  b02ffbb
