### ISSUE TITLE
Add license file to repo (or when making release)

### ISSUE THREAD

**Issue by pwolanin** [d6lts/panels#5]
LICENSE.txt is not in the release tarball

**Comment by dsnopek** [comment]
We have a script that adds the packaging information - we could have it add the LICENSE.txt too! But that would affect releases going forward - I'm not sure redoing an existing release is a good idea.

**Comment by pwolanin** [comment]
For new releases would be fine - it's not critical

**Comment by dsnopek** [comment]
We added this to the script we use to add the packaging data and used it on the most recent D6LTS release:

https://github.com/d6lts/views_send/releases/tag/6.x-1.0-rc2

So, I'm going to close this - thanks for bringing it up!
